### ISSUE TITLE
Encoding::CompatibilityError

### ISSUE THREAD

**Issue by mudongliang** [packetfu/packetfu#158] opened 2016-08-02 21:14 UTC
I tried two version of ruby 1.9.1 and 2.3.0 with packetfu 1.1.11 to execute one ruby file. However, there is always one error: `ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)`

```
/var/lib/gems/2.3.0/gems/packetfu-1.1.11/lib/packetfu/protos/tcp/header.rb:90:in `join': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
    from /var/lib/gems/2.3.0/gems/packetfu-1.1.11/lib/packetfu/protos/tcp/header.rb:90:in `to_s'
    from /var/lib/gems/2.3.0/gems/packetfu-1.1.11/lib/packetfu/protos/ip/header.rb:233:in `ip_calc_len'
    from /var/lib/gems/2.3.0/gems/packetfu-1.1.11/lib/packetfu/protos/ip/header.rb:315:in `ip_recalc'
    from /var/lib/gems/2.3.0/gems/packetfu-1.1.11/lib/packetfu/protos/ip/mixin.rb:28:in `ip_recalc'
    from /var/lib/gems/2.3.0/gems/packetfu-1.1.11/lib/packetfu/packet.rb:128:in `recalc'
    from 35580.rb:53:in `gg_client'
    from 35580.rb:187:in `<main>'
```

```
/var/lib/gems/1.9.1/gems/packetfu-1.1.11/lib/packetfu/protos/tcp/header.rb:90:in `join': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
    from /var/lib/gems/1.9.1/gems/packetfu-1.1.11/lib/packetfu/protos/tcp/header.rb:90:in `to_s'
    from /var/lib/gems/1.9.1/gems/packetfu-1.1.11/lib/packetfu/protos/ip/header.rb:233:in `ip_calc_len'
    from /var/lib/gems/1.9.1/gems/packetfu-1.1.11/lib/packetfu/protos/ip/header.rb:315:in `ip_recalc'
    from /var/lib/gems/1.9.1/gems/packetfu-1.1.11/lib/packetfu/protos/ip/mixin.rb:28:in `ip_recalc'
    from /var/lib/gems/1.9.1/gems/packetfu-1.1.11/lib/packetfu/packet.rb:128:in `recalc'
    from 35580.rb:53:in `gg_client'
    from 35580.rb:187:in `<main>'

```

How should I do to fix this problem and execute my ruby file?

**Comment by claudijd** [comment] 2016-10-20 21:10
@mudongliang can you provide some PoC/sample script logic that triggers this issue so we can debug the context?

**Comment by claudijd** [comment] 2017-04-20 04:28
@mudongliang following up on this again.  As for Ruby 1.9.1, it is 100% not supported.  If you can provide a 2.3.0 PoC to replicate the behavior I'd be happy to take a look and figure out what needs to be fixed.

**Comment by claudijd** [comment] 2017-04-24 20:39
Closing this as non-actionable due to an inability to reproduce the issue.

Please reopen this issue if you or someone else can provide reproduction steps.  Thanks!

**Closed by claudijd** 2017-04-24 20:39 UTC
Labels: bug
